[package]
name = "nicodo"
version = "0.1.0"
authors = ["rot1024 <aayhrot@gmail.com>"]
description = "Niconico-doga Comment Downloader"
edition = "2018"

[[bin]]
name = "nicodo"
path = "src/main.rs"

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
clap = "2.33.0"
futures-preview = "0.3.0-alpha.19"
futures-util-preview = "0.3.0-alpha.19"
lazy_static = "1.4.0"
quick-xml = "0.17.0"
regex = "1.3.1"
reqwest = "0.10.0-alpha.1"
select = "0.4.3"
tokio = "0.2.0-alpha.6"
